/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopupRouteImport } from './routes/topup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ApiPublicLaoQrRouteImport } from './routes/api/public/lao-qr'

const TopupRoute = TopupRouteImport.update({
  id: '/topup',
  path: '/topup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLaoQrRoute = ApiPublicLaoQrRouteImport.update({
  id: '/api/public/lao-qr',
  path: '/api/public/lao-qr',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/topup': typeof TopupRoute
  '/product/$id': typeof ProductIdRoute
  '/api/public/lao-qr': typeof ApiPublicLaoQrRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/topup': typeof TopupRoute
  '/product/$id': typeof ProductIdRoute
  '/api/public/lao-qr': typeof ApiPublicLaoQrRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/topup': typeof TopupRoute
  '/product/$id': typeof ProductIdRoute
  '/api/public/lao-qr': typeof ApiPublicLaoQrRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/history'
    | '/messages'
    | '/profile'
    | '/topup'
    | '/product/$id'
    | '/api/public/lao-qr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/history'
    | '/messages'
    | '/profile'
    | '/topup'
    | '/product/$id'
    | '/api/public/lao-qr'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/history'
    | '/messages'
    | '/profile'
    | '/topup'
    | '/product/$id'
    | '/api/public/lao-qr'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  HistoryRoute: typeof HistoryRoute
  MessagesRoute: typeof MessagesRoute
  ProfileRoute: typeof ProfileRoute
  TopupRoute: typeof TopupRoute
  ProductIdRoute: typeof ProductIdRoute
  ApiPublicLaoQrRoute: typeof ApiPublicLaoQrRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topup': {
      id: '/topup'
      path: '/topup'
      fullPath: '/topup'
      preLoaderRoute: typeof TopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lao-qr': {
      id: '/api/public/lao-qr'
      path: '/api/public/lao-qr'
      fullPath: '/api/public/lao-qr'
      preLoaderRoute: typeof ApiPublicLaoQrRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  HistoryRoute: HistoryRoute,
  MessagesRoute: MessagesRoute,
  ProfileRoute: ProfileRoute,
  TopupRoute: TopupRoute,
  ProductIdRoute: ProductIdRoute,
  ApiPublicLaoQrRoute: ApiPublicLaoQrRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
